### ISSUE TITLE
Enhancement: sort alphabetically My iTwins list

### ISSUE THREAD

**Issue by aleksas-lukauskas** [iTwin/admin-components-react#85]
Sort alphabetically (case insensitive) My iTwins list except for "Recent" type iTwins (as it is now) because they should be sorted by last used time. At least "All" type should be sorted for a better user experience when looking for a needed iTwin.
![image](https://github.com/iTwin/my-itwins/assets/83806085/5a700a39-c08c-42a5-8542-6a75de8c0a53)

#[178](https://github.com/iTwin/my-itwins/issues/178)

**Comment by williamkbentley** [comment]
This can be down with the `postProcessCallback` prop that was introduced in #47. For example:

```ts
  const sortByName = React.useCallback(
    (iTwins: ITwinFull[], fetchStatus: DataStatus | undefined) => {
      if (fetchStatus !== DataStatus.Complete) {
        return iTwins;
      }

      return iTwins.sort((a, b) => a.displayName?.localeCompare(b.displayName));
    },
    []
  );
// ...
<ITwinGrid postProcessCallback={sortByName} />
```

**Comment by aleksas-lukauskas** [comment]
Verified. Comments on the #https://github.com/iTwin/my-itwins/issues/178
