### ISSUE TITLE
node 18 support

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/admin-components-react#93]
[Node 18 has been LTS for 10 months; node 16 is in maintenance and reaches EOL in a week](https://github.com/nodejs/Release) 
Verify packages work with v18/update versions in rush.json.

**Comment by raplemie** [comment]
The main offender is node-sass, and that is used in bentley-react-scritps 4.0.3. I tried to move that to 5.0.5 but this is throwing a load of error, so we will need someone to look into that at some point.

**Comment by ben-polinsky** [comment]
> The main offender is node-sass, and that is used in bentley-react-scritps 4.0.3. I tried to move that to 5.0.5 but this is throwing a load of error, so we will need someone to look into that at some point.

I looked into it a bit yesterday, seems to work if you replace `node-sass` with `sass` in `package/modules/*`

I can get a PR in since I have it done locally.
